Importar tensorFlow

In [19]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


Cargar dataset-->mnist

In [20]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Crear un modelo de machine learning
crear un tf.keras.Sequential apilando capas:

In [21]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

Por ejemplo, el modelo devuelve un vector de logits o log-odds scores, para cada clase.

In [22]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01852623, -0.7050208 , -0.22586891, -0.64592993, -0.28346527,
        -0.16747312,  0.3761456 , -0.12999766,  0.00779954,  0.45522398]],
      dtype=float32)

tf.nn.softmax --> convierte los logits a probabilidad

In [23]:
tf.nn.softmax(predictions).numpy()

array([[0.10891825, 0.05282849, 0.08530239, 0.05604424, 0.08052809,
        0.090432  , 0.15574451, 0.09388529, 0.10775615, 0.1685606 ]],
      dtype=float32)

definir funcion de perdidas-->devuelve un escalar

In [24]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

la perdida es igual to the negative log probability de la clase true; la perdida es 0 si el modelo asegura la clase correcta.

In [25]:
loss_fn(y_train[:1], predictions).numpy()

2.4031572

antes de empezar, se tiene que configurar y compilar el modelo usando Keras model.compile

In [26]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Entrenar y evaluar el modelo;
usar el metodo model.fit para ajustar los parametros del modelo y minimizar las perdidas. 

In [27]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2969 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1430 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1066 - accuracy: 0.9682
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0885 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0743 - accuracy: 0.9761


model.evaluate evalua el rendimiento del modelo, normalmente en un set de validacion o test.

In [28]:
model.evaluate(x_test ,y_test, verbose=2)

313/313 - 1s - loss: 0.0740 - accuracy: 0.9781 - 896ms/epoch - 3ms/step


[0.07402949780225754, 0.9781000018119812]

El clasificador de imagenes esta estrenado al 97% de precision en el dataset mnist.

Si queremos que el modelo devuelva la probabilidad, podemos adjuntar el softmax al modelo entrenado.

In [33]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [34]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.04367693e-07, 6.18656282e-09, 3.45002036e-07, 4.96988687e-05,
        8.71102426e-11, 2.81038382e-07, 4.12331437e-14, 9.99946952e-01,
        4.28448971e-07, 2.14739339e-06],
       [5.61523361e-09, 1.28156884e-04, 9.99869466e-01, 1.86198292e-06,
        5.33243578e-15, 1.80456922e-07, 6.23468477e-09, 5.93992222e-14,
        3.33421838e-07, 2.94110270e-14],
       [8.26340880e-08, 9.99437511e-01, 1.35295850e-04, 9.94602851e-06,
        7.54924549e-05, 1.20303348e-05, 1.46084403e-05, 2.12840707e-04,
        1.01058606e-04, 1.09801795e-06],
       [9.99929190e-01, 4.45198239e-10, 1.08620952e-05, 7.73524960e-07,
        1.15163482e-06, 2.77885647e-07, 1.24685153e-06, 1.43382329e-06,
        7.96336792e-07, 5.41693698e-05],
       [3.04531000e-07, 2.04165504e-10, 1.40058739e-06, 9.88556526e-09,
        9.98476923e-01, 7.16140107e-08, 1.06752043e-06, 7.19878790e-06,
        8.31282705e-07, 1.51216937e-03]], dtype=float32)>

Conclusion

se ha entrenado un dataset usando la API de keras.